# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  # Pods for Test

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.0'
  end

  target 'TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
